/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package com.instras;

import java.awt.Color;
import java.awt.Graphics2D;
import java.awt.image.BufferedImage;
import javax.swing.ImageIcon;

/**
 *
 * @author nathan
 */
public class JQyncFrame extends javax.swing.JFrame {

    /**
     * Creates new form JQyncFrame
     */
    public JQyncFrame() {
        initComponents();
    }
    
    public void displayImage(BufferedImage bufferedImage, int MAX_X, int MAX_Y) {
        int width = MAX_X/4;
        int height = MAX_Y/4;
        
        BufferedImage syncImage = new BufferedImage(width, height,bufferedImage.getType());

        Graphics2D g2 = syncImage.createGraphics();
        g2.setBackground(Color.WHITE);
        g2.drawImage(bufferedImage, 0, 0, width, height, null);
        g2.dispose();
        
        ImageIcon icon = new ImageIcon(syncImage);
        imageLabel.setIcon(icon);
    }
    
    /**
     * Method to display the result from a calculation
     * @param result 
     */
    public void displayResult(String result) {
        calcLabel.setText(result); 
    }
    
    /**
     * Method to display the expression buffer in real time
     * @param toString 
     */
    public void displayExpression(String expression) {
        expressionTextField.setText(expression);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        closeButton = new javax.swing.JButton();
        imagePane = new javax.swing.JScrollPane();
        imageLabel = new javax.swing.JLabel();
        calcLabel = new javax.swing.JLabel();
        expressionTextField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("jQync Version 0.1");

        closeButton.setText("Close");
        closeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeButtonActionPerformed(evt);
            }
        });

        imageLabel.setBackground(java.awt.Color.white);
        imageLabel.setForeground(java.awt.Color.white);
        imagePane.setViewportView(imageLabel);

        calcLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        calcLabel.setForeground(new java.awt.Color(0, 102, 0));
        calcLabel.setText("No input");

        expressionTextField.setEditable(false);
        expressionTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                expressionTextFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(imagePane, javax.swing.GroupLayout.DEFAULT_SIZE, 410, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(calcLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(closeButton))
            .addComponent(expressionTextField, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(imagePane, javax.swing.GroupLayout.DEFAULT_SIZE, 309, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(expressionTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(closeButton)
                    .addComponent(calcLabel)))
        );

        calcLabel.getAccessibleContext().setAccessibleName("Blank");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void closeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeButtonActionPerformed
        System.exit(0);
    }//GEN-LAST:event_closeButtonActionPerformed

    private void expressionTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_expressionTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_expressionTextFieldActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel calcLabel;
    private javax.swing.JButton closeButton;
    private javax.swing.JTextField expressionTextField;
    private javax.swing.JLabel imageLabel;
    private javax.swing.JScrollPane imagePane;
    // End of variables declaration//GEN-END:variables

}
